name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.0.1"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  Server_Addr: .slzn.fun
  Server_Port: 17000
  User: admin123
  Meta_token: passwd123
schema:
  server_addr: str
  server_port: int
  user: str
  meta_token: str
  
